# Application Configuration
spring.application.name=mess-breakfast

# Server Port
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/hostel_mess
spring.data.mongodb.database=hostel_mess

# Logging
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.com.hostel.mess=DEBUG
